#pragma once
#include <typeindex>
#include <natRefObj.h>
#include <natException.h>
#include <natDelegate.h>

using namespace NatsuLib;

DeclareException(ReflectionException, natException, _T("Exception generated by reflection"));

class ArgumentPack;

struct Interface
	: natRefObj
{
};

struct Object;
struct IType;

struct IMethod
	: Interface
{
	virtual bool Match(ArgumentPack const& pack) = 0;
	virtual natRefPointer<Object> Invoke(ArgumentPack const& pack) = 0;
	virtual bool CompatWith(ArgumentPack const& pack) const noexcept = 0;
	virtual natRefPointer<IType> GetReturnType() const noexcept = 0;
};

struct IMemberMethod
	: Interface
{
	virtual bool Match(natRefPointer<Object> object, ArgumentPack const& pack) = 0;
	virtual natRefPointer<Object> Invoke(natRefPointer<Object> object, ArgumentPack const& pack) = 0;
	virtual bool CompatWith(natRefPointer<Object> object, ArgumentPack const& pack) const noexcept = 0;
	virtual natRefPointer<IType> GetReturnType() const noexcept = 0;
};

////////////////////////////////////////////////////////////////////////////////
/// @brief	类型接口
////////////////////////////////////////////////////////////////////////////////
struct IType : Interface
{
	virtual void RegisterNonMemberMethod(ncTStr name, natRefPointer<IMethod> method) = 0;
	virtual void RegisterMemberMethod(ncTStr name, natRefPointer<IMemberMethod> method) = 0;

	virtual ncTStr GetName() const noexcept = 0;
	virtual natRefPointer<Object> Construct(ArgumentPack const& args) = 0;
	virtual natRefPointer<Object> InvokeNonMember(ncTStr name, ArgumentPack const& args) = 0;
	virtual natRefPointer<Object> InvokeMember(natRefPointer<Object> object, ncTStr name, ArgumentPack const& args) = 0;

	/// @brief	枚举该类型下的非成员，当枚举函数返回true时立即结束枚举
	/// @param	enumFunc	枚举函数，接受参数的含义为 非成员名，是否为方法，非方法的类型（若是方法则为nullptr），返回bool值
	/// @return	是否因枚举函数返回true而结束枚举
	virtual bool EnumNonMember(Delegate<bool(ncTStr, bool, natRefPointer<IType>)> enumFunc) const = 0;

	/// @brief	枚举该类型下的成员，当枚举函数返回true时立即结束枚举
	/// @param	enumFunc	枚举函数，接受参数的含义为 成员名，是否为方法，非方法的类型（若是方法则为nullptr），返回bool值
	/// @return	是否因枚举函数返回true而结束枚举
	virtual bool EnumMember(Delegate<bool(ncTStr, bool, natRefPointer<IType>)> enumFunc) const = 0;

	virtual std::type_index GetTypeIndex() const noexcept = 0;
	virtual bool Equal(const IType* other) const noexcept = 0;

	virtual bool IsConvertable(natRefPointer<IType> other) const noexcept = 0;
	virtual natRefPointer<Object> ConvertTo(natRefPointer<Object> object, NatsuLib::natRefPointer<IType> toType) const = 0;
};
